name: github pages

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Debug0
        run: cat MenuGenerator2/wwwroot/index.html

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
        
      # Publishes Blazor project to the release-folder
      - name: Build .NET Core Project
        run: dotnet build MenuGenerator2/MenuGenerator2.csproj -c:Release
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish MenuGenerator2/MenuGenerator2.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
        
      - name: Debug
        run: cat dist/Web/wwwroot/index.html
        
      - name: Add .nojekyll file
        run: touch dist/Web/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/Web/wwwroot
